import type { Metadata, Viewport } from "next";
import "../../public/scss/main.scss";
import Provider from "@/state/provider";
import { Loader } from "@react-three/drei";

export const metadata: Metadata = {
  title: "3D Chair Configurator",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  minimumScale: 1,
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </Provider>
  );
}
